import React, { useEffect, useState, useCallback, useRef } from 'react';
import {
  Video, Search, Trash2, Calendar, Users, FileText,
  CheckCircle2, AlertCircle, HelpCircle, Sparkles, Plus,
  Clipboard, ClipboardCheck, Printer, X, MessageSquare, Send, Bot
} from 'lucide-react';
import StatusBadge from '../components/StatusBadge';
import PriorityBadge from '../components/PriorityBadge';
import { fetchMeetings, fetchMeetingDetails, deleteMeeting, updateActionItem, askMeetingQuestion } from '../api/client';

/* ── Debounce hook ──────────────────────────────────────────── */
function useDebounce(value, delay = 350) {
  const [debounced, setDebounced] = useState(value);
  useEffect(() => {
    const t = setTimeout(() => setDebounced(value), delay);
    return () => clearTimeout(t);
  }, [value, delay]);
  return debounced;
}

/* ── Format meeting as plain-text for clipboard ─────────────── */
function formatMeetingAsText(m) {
  const lines = [];
  lines.push(`MEETING SUMMARY — ${m.title}`);
  lines.push(`Date: ${m.date}  |  Participants: ${m.participants || 'N/A'}`);
  lines.push('═'.repeat(60));

  lines.push('\nPURPOSE');
  lines.push(m.summary?.purpose || '—');

  if (m.summary?.discussion_points?.length) {
    lines.push('\nKEY DISCUSSION POINTS');
    m.summary.discussion_points.forEach((p) => lines.push(`  • ${p}`));
  }

  if (m.summary?.major_outcomes?.length) {
    lines.push('\nMAJOR OUTCOMES');
    m.summary.major_outcomes.forEach((o) => lines.push(`  ✓ ${o}`));
  }

  if (m.summary?.concerns?.length) {
    lines.push('\nCONCERNS & BLOCKERS');
    m.summary.concerns.forEach((c) => lines.push(`  ⚠ ${c}`));
  }

  if (m.summary?.next_steps?.length) {
    lines.push('\nNEXT STEPS');
    m.summary.next_steps.forEach((s) => lines.push(`  → ${s}`));
  }

  if (m.key_decisions?.length) {
    lines.push('\nKEY DECISIONS');
    m.key_decisions.forEach((d) => lines.push(`  ✓ ${d}`));
  }

  if (m.action_items?.length) {
    lines.push('\nACTION ITEMS');
    lines.push(
      `${'Task'.padEnd(40)}${'Owner'.padEnd(20)}${'Due'.padEnd(20)}${'Priority'.padEnd(10)}Status`
    );
    lines.push('-'.repeat(100));
    m.action_items.forEach((a) =>
      lines.push(
        `${(a.task || '').substring(0, 38).padEnd(40)}${(a.owner || '').padEnd(20)}${(a.due_date || '').padEnd(20)}${(a.priority || '').padEnd(10)}${a.status}`
      )
    );
  }

  lines.push('\n' + '═'.repeat(60));
  lines.push('Generated by AI Meeting Tracker — Gemini 2.5 Flash');
  return lines.join('\n');
}

export default function MeetingsPage({ selectedMeetingId, setSelectedMeetingId, onOpenNewMeeting }) {
  const [meetings, setMeetings] = useState([]);
  const [search, setSearch] = useState('');
  const [activeMeeting, setActiveMeeting] = useState(null);
  const [loading, setLoading] = useState(true);
  const [loadingDetails, setLoadingDetails] = useState(false);
  const [copied, setCopied] = useState(false);
  const printRef = useRef(null);

  // Chat State
  const [chatQuery, setChatQuery] = useState('');
  const [chatHistory, setChatHistory] = useState([]);
  const [isChatting, setIsChatting] = useState(false);
  const [isChatOpen, setIsChatOpen] = useState(false);

  const debouncedSearch = useDebounce(search);

  /* ── Load meetings list (re-runs on debounced search) ───────── */
  const loadMeetings = useCallback(async () => {
    setLoading(true);
    try {
      const data = await fetchMeetings(debouncedSearch);
      setMeetings(data);
      // Auto-select first only when no explicit selection and not searching
      if (data.length > 0 && !selectedMeetingId && !debouncedSearch) {
        loadMeetingDetail(data[0].id);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [debouncedSearch]);

  useEffect(() => { loadMeetings(); }, [loadMeetings]);

  useEffect(() => {
    if (selectedMeetingId) loadMeetingDetail(selectedMeetingId);
  }, [selectedMeetingId]);

  /* ── Meeting detail fetch ───────────────────────────────────── */
  const loadMeetingDetail = async (id) => {
    setLoadingDetails(true);
    try {
      const detail = await fetchMeetingDetails(id);
      setActiveMeeting(detail);
      setSelectedMeetingId(id);
      // Reset chat when switching meetings
      setChatHistory([]);
      setIsChatOpen(false);
      setChatQuery('');
    } catch (err) {
      console.error(err);
    } finally {
      setLoadingDetails(false);
    }
  };

  /* ── Delete ─────────────────────────────────────────────────── */
  const handleDeleteMeeting = async (id, e) => {
    e.stopPropagation();
    if (!window.confirm('Delete this meeting and all its action items?')) return;
    try {
      await deleteMeeting(id);
      if (activeMeeting?.id === id) {
        setActiveMeeting(null);
        setSelectedMeetingId(null);
      }
      loadMeetings();
    } catch (err) {
      console.error(err);
    }
  };

  /* ── Inline action item status change ───────────────────────── */
  const handleStatusChange = async (taskId, newStatus) => {
    try {
      await updateActionItem(taskId, { status: newStatus });
      if (activeMeeting) loadMeetingDetail(activeMeeting.id);
    } catch (err) {
      console.error(err);
    }
  };

  /* ── Copy summary to clipboard ──────────────────────────────── */
  const handleCopy = async () => {
    if (!activeMeeting) return;
    const text = formatMeetingAsText(activeMeeting);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback for non-secure contexts
      const el = document.createElement('textarea');
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand('copy');
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  /* ── Export / Print PDF ─────────────────────────────────────── */
  const handlePrint = () => {
    window.print();
  };

  /* ── Chat with AI ───────────────────────────────────────────── */
  const handleSendChat = async (e) => {
    e.preventDefault();
    if (!chatQuery.trim() || !activeMeeting) return;

    const userMessage = chatQuery.trim();
    setChatQuery('');
    setChatHistory(prev => [...prev, { role: 'user', content: userMessage }]);
    setIsChatting(true);

    try {
      const response = await askMeetingQuestion(activeMeeting.id, userMessage);
      setChatHistory(prev => [...prev, { role: 'ai', content: response.answer }]);
    } catch (err) {
      setChatHistory(prev => [...prev, { role: 'ai', content: `Error: ${err.message}` }]);
    } finally {
      setIsChatting(false);
    }
  };

  return (
    <>
      {/* ── Print-only stylesheet ─────────────────────────── */}
      <style>{`
        @media print {
          body * { visibility: hidden !important; }
          #print-meeting-detail, #print-meeting-detail * { visibility: visible !important; }
          #print-meeting-detail {
            position: absolute !important;
            top: 0; left: 0;
            width: 100%;
            background: white !important;
            color: black !important;
            padding: 24px;
          }
          .no-print { display: none !important; }
        }
      `}</style>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 pb-12">

        {/* ── LEFT: Meeting sidebar list ─────────────────── */}
        <div className="lg:col-span-4 space-y-4 no-print">
          <div className="flex items-center justify-between">
            <h2 className="text-base font-bold text-slate-100 flex items-center gap-2">
              <Video className="w-4 h-4 text-indigo-400" />
              Meetings Record
            </h2>
            <button
              onClick={onOpenNewMeeting}
              className="p-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-1 text-xs font-semibold shadow-md shadow-indigo-600/30"
            >
              <Plus className="w-3.5 h-3.5" />
              New
            </button>
          </div>

          {/* Live search — queries backend by title + participants */}
          <div className="relative">
            <Search className="w-4 h-4 text-slate-500 absolute left-3 top-3" />
            <input
              type="text"
              placeholder="Search title or participants…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-9 pr-8 py-2 bg-slate-900 border border-slate-800 rounded-xl text-xs text-slate-200 focus:outline-none focus:border-indigo-500"
            />
            {search && (
              <button
                onClick={() => setSearch('')}
                className="absolute right-2.5 top-2.5 text-slate-500 hover:text-slate-300"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            )}
          </div>
          {search && !loading && (
            <p className="text-[11px] text-slate-500 -mt-1">
              {meetings.length} result{meetings.length !== 1 ? 's' : ''} for "{search}"
            </p>
          )}

          {/* List */}
          {loading ? (
            <div className="py-8 text-center text-xs text-slate-500 flex items-center justify-center gap-2">
              <Sparkles className="w-4 h-4 animate-spin text-indigo-400" />
              Searching meetings...
            </div>
          ) : meetings.length === 0 ? (
            <div className="py-12 text-center border border-dashed border-slate-700/50 bg-slate-900/30 rounded-2xl flex flex-col items-center justify-center mt-2 mx-1">
              <div className="w-12 h-12 bg-indigo-500/10 rounded-full flex items-center justify-center mb-3 border border-indigo-500/20">
                <Video className="w-6 h-6 text-indigo-400" />
              </div>
              <p className="text-sm font-semibold text-slate-300 mb-1">
                {search ? "No matches found" : "No meetings yet"}
              </p>
              <p className="text-xs text-slate-500 mb-4 max-w-[200px]">
                {search ? `We couldn't find any meetings matching "${search}".` : "You haven't recorded any meetings. Let's change that!"}
              </p>
              {!search && (
                <button onClick={onOpenNewMeeting} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-lg shadow-indigo-600/30 transition-all border border-indigo-500/20">
                  <Plus className="w-4 h-4" />
                  Create Meeting
                </button>
              )}
            </div>
          ) : (
            <div className="space-y-2.5 max-h-[75vh] overflow-y-auto pr-1">
              {meetings.map((m) => {
                const isSelected = activeMeeting?.id === m.id;
                return (
                  <div
                    key={m.id}
                    onClick={() => loadMeetingDetail(m.id)}
                    className={`p-3.5 rounded-xl border transition-all cursor-pointer flex items-center justify-between ${
                      isSelected
                        ? 'bg-indigo-950/40 border-indigo-500/50 shadow-md shadow-indigo-950/50'
                        : 'bg-slate-900/60 border-slate-800 hover:border-slate-700'
                    }`}
                  >
                    <div className="space-y-1 min-w-0 pr-2">
                      <h3 className="text-xs font-semibold text-slate-200 truncate">{m.title}</h3>
                      <div className="flex items-center gap-2 text-[11px] text-slate-400">
                        <span className="flex items-center gap-1">
                          <Calendar className="w-3 h-3 text-slate-500" />
                          {m.date}
                        </span>
                        <span>•</span>
                        <span className="text-indigo-400 font-medium">{m.action_items_count} tasks</span>
                      </div>
                      {m.participants && (
                        <p className="text-[10px] text-slate-500 truncate">{m.participants}</p>
                      )}
                    </div>
                    <button
                      onClick={(e) => handleDeleteMeeting(m.id, e)}
                      title="Delete Meeting"
                      className="p-1.5 text-slate-500 hover:text-rose-400 hover:bg-rose-500/10 rounded-lg transition-all shrink-0"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* ── RIGHT: Meeting detail ──────────────────────── */}
        <div className="lg:col-span-8">
          {loadingDetails ? (
            <div className="glass-card rounded-2xl p-12 border border-slate-800 flex items-center justify-center min-h-[50vh]">
              <div className="flex items-center gap-3 text-indigo-400 text-sm">
                <Sparkles className="w-5 h-5 animate-spin" />
                Fetching AI Breakdown...
              </div>
            </div>
          ) : !activeMeeting ? (
            <div className="glass-card rounded-2xl p-12 border border-slate-800 text-center min-h-[50vh] flex flex-col items-center justify-center">
              <Video className="w-12 h-12 text-slate-700 mb-3" />
              <p className="text-sm font-medium text-slate-300">No meeting selected</p>
              <p className="text-xs text-slate-500 max-w-sm mt-1">
                Select a meeting from the list or create a new one to view structured AI insights.
              </p>
            </div>
          ) : (
            <div id="print-meeting-detail" ref={printRef} className="space-y-6">

              {/* ── Header Card with Export Buttons ─────── */}
              <div className="glass-card rounded-2xl p-6 border border-slate-800 space-y-3">
                <div className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-800/80 pb-3">
                  <div>
                    <h1 className="text-lg font-bold text-slate-100">{activeMeeting.title}</h1>
                    <div className="flex flex-wrap items-center gap-4 text-xs text-slate-400 mt-1">
                      <span className="flex items-center gap-1.5">
                        <Calendar className="w-3.5 h-3.5 text-indigo-400" />
                        {activeMeeting.date}
                      </span>
                      {activeMeeting.participants && (
                        <span className="flex items-center gap-1.5">
                          <Users className="w-3.5 h-3.5 text-purple-400" />
                          {activeMeeting.participants}
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Export Buttons */}
                  <div className="flex items-center gap-2 no-print">
                    <button
                      onClick={handleCopy}
                      title="Copy summary to clipboard"
                      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl border text-xs font-medium transition-all ${
                        copied
                          ? 'border-emerald-500/50 bg-emerald-500/10 text-emerald-400'
                          : 'border-slate-700 bg-slate-900 text-slate-300 hover:border-indigo-500/50 hover:text-indigo-300'
                      }`}
                    >
                      {copied ? (
                        <><ClipboardCheck className="w-3.5 h-3.5" /> Copied!</>
                      ) : (
                        <><Clipboard className="w-3.5 h-3.5" /> Copy Summary</>
                      )}
                    </button>

                    <button
                      onClick={handlePrint}
                      title="Export as PDF via browser print"
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-slate-700 bg-slate-900 text-slate-300 hover:border-indigo-500/50 hover:text-indigo-300 text-xs font-medium transition-all"
                    >
                      <Printer className="w-3.5 h-3.5" />
                      Export PDF
                    </button>

                    <span className="px-3 py-1 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                      {activeMeeting.action_items.length} Action Items
                    </span>
                  </div>
                </div>

                {/* Purpose */}
                {activeMeeting.summary?.purpose && (
                  <div className="p-3.5 rounded-xl bg-indigo-950/30 border border-indigo-500/20">
                    <h4 className="text-xs font-bold text-indigo-300 uppercase tracking-wider mb-1">
                      Core Objective / Purpose
                    </h4>
                    <p className="text-xs text-slate-200 leading-relaxed">{activeMeeting.summary.purpose}</p>
                  </div>
                )}
              </div>

              {/* ── 2-col Summary Grid ───────────────────── */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Discussion Points */}
                <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-2">
                  <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-2">
                    <FileText className="w-4 h-4 text-indigo-400" />
                    Key Discussion Points
                  </h3>
                  <ul className="space-y-1.5 pt-1">
                    {activeMeeting.summary?.discussion_points?.map((pt, idx) => (
                      <li key={idx} className="text-xs text-slate-300 flex items-start gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 mt-1.5 shrink-0" />
                        {pt}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Major Outcomes */}
                <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-2">
                  <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    Major Outcomes
                  </h3>
                  <ul className="space-y-1.5 pt-1">
                    {activeMeeting.summary?.major_outcomes?.map((out, idx) => (
                      <li key={idx} className="text-xs text-slate-300 flex items-start gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0" />
                        {out}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Concerns */}
                <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-2">
                  <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 text-rose-400" />
                    Concerns & Blockers
                  </h3>
                  <ul className="space-y-1.5 pt-1">
                    {activeMeeting.summary?.concerns?.map((c, idx) => (
                      <li key={idx} className="text-xs text-slate-300 flex items-start gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-rose-400 mt-1.5 shrink-0" />
                        {c}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Next Steps */}
                <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-2">
                  <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-2">
                    <HelpCircle className="w-4 h-4 text-amber-400" />
                    General Next Steps
                  </h3>
                  <ul className="space-y-1.5 pt-1">
                    {activeMeeting.summary?.next_steps?.map((ns, idx) => (
                      <li key={idx} className="text-xs text-slate-300 flex items-start gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-1.5 shrink-0" />
                        {ns}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* ── Key Decisions ─────────────────────────── */}
              {activeMeeting.key_decisions?.length > 0 && (
                <div className="glass-card rounded-2xl p-5 border border-purple-500/30 bg-purple-950/20 space-y-2">
                  <h3 className="text-xs font-bold text-purple-300 uppercase tracking-wider flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-purple-400" />
                    Key Decisions Agreed Upon
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2 pt-1">
                    {activeMeeting.key_decisions.map((dec, idx) => (
                      <div
                        key={idx}
                        className="p-2.5 rounded-xl bg-purple-900/30 border border-purple-500/20 text-xs text-purple-200 font-medium"
                      >
                        ✓ {dec}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* ── Action Items Table ────────────────────── */}
              <div className="glass-card rounded-2xl p-6 border border-slate-800 space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-bold text-slate-100">
                    Extracted Action Items ({activeMeeting.action_items.length})
                  </h3>
                  <span className="text-xs text-slate-400 no-print">Change status inline ↓</span>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs">
                    <thead>
                      <tr className="border-b border-slate-800 text-slate-400 font-semibold uppercase tracking-wider">
                        <th className="py-2.5 px-3">Task</th>
                        <th className="py-2.5 px-3">Owner</th>
                        <th className="py-2.5 px-3">Due Date</th>
                        <th className="py-2.5 px-3">Priority</th>
                        <th className="py-2.5 px-3">Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800/60">
                      {activeMeeting.action_items.map((item) => (
                        <tr key={item.id} className="hover:bg-slate-900/40">
                          <td className="py-3 px-3 font-medium text-slate-200 max-w-xs">{item.task}</td>
                          <td className="py-3 px-3 text-slate-300 font-semibold">{item.owner}</td>
                          <td className="py-3 px-3 text-slate-400">{item.due_date}</td>
                          <td className="py-3 px-3">
                            <PriorityBadge priority={item.priority} />
                          </td>
                          <td className="py-3 px-3 no-print">
                            <StatusBadge
                              status={item.status}
                              editable={true}
                              onStatusChange={(s) => handleStatusChange(item.id, s)}
                            />
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* ── Raw Transcript Collapsible ────────────── */}
              <details className="glass-card rounded-2xl p-5 border border-slate-800 text-xs text-slate-400 no-print">
                <summary className="font-semibold text-slate-300 cursor-pointer hover:text-indigo-400">
                  View Raw Meeting Transcript
                </summary>
                <pre className="mt-3 p-4 bg-slate-950 rounded-xl text-slate-300 font-mono whitespace-pre-wrap leading-relaxed border border-slate-800">
                  {activeMeeting.transcript}
                </pre>
              </details>

              {/* ── Ask AI Chat Panel ───────────────────────────── */}
              <div className="glass-card rounded-2xl border border-indigo-500/30 overflow-hidden no-print shadow-lg shadow-indigo-900/20">
                <div 
                  className="p-4 bg-indigo-950/40 cursor-pointer flex items-center justify-between hover:bg-indigo-900/30 transition-colors"
                  onClick={() => setIsChatOpen(!isChatOpen)}
                >
                  <div className="flex items-center gap-2">
                    <Bot className="w-5 h-5 text-indigo-400" />
                    <h3 className="text-sm font-bold text-indigo-100">Ask AI About This Meeting</h3>
                  </div>
                  <div className="text-xs text-indigo-300 font-medium bg-indigo-500/20 px-2.5 py-1 rounded-full border border-indigo-500/20">
                    {isChatOpen ? 'Close Chat' : 'Open Chat'}
                  </div>
                </div>

                {isChatOpen && (
                  <div className="flex flex-col h-[400px]">
                    <div className="flex-1 p-5 overflow-y-auto space-y-4 bg-slate-900/40 border-t border-indigo-500/20">
                      {chatHistory.length === 0 ? (
                        <div className="h-full flex flex-col items-center justify-center text-center space-y-3 opacity-60">
                          <MessageSquare className="w-8 h-8 text-indigo-400" />
                          <p className="text-xs text-slate-300 max-w-[250px]">
                            Ask questions about this meeting's transcript, decisions, or action items.
                          </p>
                        </div>
                      ) : (
                        chatHistory.map((msg, idx) => (
                          <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                            <div className={`max-w-[80%] rounded-2xl p-3.5 text-xs shadow-sm ${
                              msg.role === 'user' 
                                ? 'bg-indigo-600 text-white rounded-tr-sm' 
                                : 'bg-slate-800 text-slate-200 border border-slate-700 rounded-tl-sm'
                            }`}>
                              {msg.role === 'ai' && <Bot className="w-3.5 h-3.5 mb-1.5 text-indigo-400" />}
                              <div className="whitespace-pre-wrap leading-relaxed">{msg.content}</div>
                            </div>
                          </div>
                        ))
                      )}
                      {isChatting && (
                        <div className="flex justify-start">
                          <div className="max-w-[80%] rounded-2xl p-3.5 text-xs bg-slate-800 text-slate-400 border border-slate-700 rounded-tl-sm flex items-center gap-2">
                            <Sparkles className="w-3.5 h-3.5 animate-pulse text-indigo-400" />
                            Thinking...
                          </div>
                        </div>
                      )}
                    </div>
                    
                    <form onSubmit={handleSendChat} className="p-3 border-t border-slate-800 bg-slate-900 flex gap-2">
                      <input
                        type="text"
                        value={chatQuery}
                        onChange={(e) => setChatQuery(e.target.value)}
                        placeholder="E.g. What was decided about the budget?"
                        className="flex-1 bg-slate-950 border border-slate-800 rounded-xl px-4 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500 transition-colors"
                        disabled={isChatting}
                      />
                      <button
                        type="submit"
                        disabled={!chatQuery.trim() || isChatting}
                        className="bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed text-white p-2.5 rounded-xl transition-colors shrink-0 shadow-md shadow-indigo-600/20"
                      >
                        <Send className="w-4 h-4" />
                      </button>
                    </form>
                  </div>
                )}
              </div>

            </div>
          )}
        </div>

      </div>
    </>
  );
}
